### ISSUE TITLE
Colobot Gold is missing

### ISSUE THREAD

**Issue by pandruszkow** [pandruszkow-contrib/osgameclones#1]
https://colobot.info/

New game

```yaml
- name:
  type: # One of: remake, clone
  originals: []
  repo:
  url:
  feed:
  development: # One of: complete, very active, active, sporadic, halted
  status: # One of: playable, semi-playable, unplayable
  multiplayer: []
  lang: []
  framework: []
  license:
  content: # One of: commercial, free, open, swappable*
  info:
  updated: # insert current date
  images:
    -
  video:
    youtube: # YouTube video ID
    vimeo: # Vimeo video ID
```
